# Generated by Django 4.1.7 on 2023-04-14 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=300, verbose_name='Имя ресурса')),
                ('name', models.URLField(max_length=300, verbose_name='Адрес')),
                ('login', models.CharField(max_length=300, verbose_name='Логин')),
                ('password', models.CharField(max_length=300, verbose_name='Пароль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пароль',
                'verbose_name_plural': 'Пароли',
            },
        ),
    ]
