# Generated by Django 4.2.3 on 2023-08-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_userfiles_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFiles',
        ),
    ]
