# Generated by Django 4.2 on 2023-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_userfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiles',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
    ]
