# Generated by Django 4.2.3 on 2023-08-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_category_task_delete_userpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_gone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
