# Generated by Django 4.2.3 on 2023-08-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_task_is_gone_alter_task_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cathegory',
        ),
        migrations.RemoveField(
            model_name='task',
            name='email_b',
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала / Дата загрузки'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
