# Generated by Django 4.2.3 on 2023-09-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_task_cathegory_remove_task_email_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ip_adress',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
    ]
